import table from './opencode-go-effort-profiles.json';
import type { EffortProfile } from '../effort-policy.js';

/**
 * Reviewed effort profiles for the retained OpenCode Go catalog.
 *
 * Generated by `pnpm update:opencode-go` from clodex's validated wire maps, with
 * the committed resolver snapshot providing cross-check evidence only, and
 * re-verified offline by `pnpm update:opencode-go -- --check`. Nothing here is
 * discovered at runtime:
 * a profile is attached by model identity AFTER retained-identity projection,
 * so it can never arrive from a persisted model cache or from models.dev.
 *
 * Frozen because it is one shared authority read on every request path; a
 * consumer that edited a level in place would change what every later request
 * sends.
 */
function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object') {
    for (const nested of Object.values(value)) deepFreeze(nested);
    Object.freeze(value);
  }
  return value;
}

const PROFILES_BY_ID: ReadonlyMap<string, EffortProfile> = new Map(
  deepFreeze(table.profiles as unknown as EffortProfile[])
    .map(profile => [profile.modelId, profile] as const),
);

export function openCodeGoEffortProfile(modelId: string): EffortProfile | undefined {
  return PROFILES_BY_ID.get(modelId);
}
